<center> <img src = https://raw.githubusercontent.com/AndreyRysistov/DatasetsForPandas/main/hh%20label.jpg alt="drawing" style="width:400px;">

# <center> Проект: Анализ вакансий из HeadHunter

In [25]:
import pandas as pd
from sqlalchemy import create_engine
import psycopg2
import requests
from bs4 import BeautifulSoup

In [26]:
# вставьте сюда параметры подключения из юнита 1. Работа с базой данных из Python
DBNAME = 'project_sql'
USER = 'skillfactory'
PASSWORD = 'cCkxxLVrDE8EbvjueeMedPKt'
HOST = '84.201.134.129'
PORT = 5432

connection_string = f"postgresql://{USER}:{PASSWORD}@{HOST}:{PORT}/{DBNAME}"

In [27]:
connection = psycopg2.connect(
    dbname=DBNAME,
    user=USER,
    host=HOST,
    password=PASSWORD,
    port=PORT
)

connection_string = f"postgresql://{USER}:{PASSWORD}@{HOST}:{PORT}/{DBNAME}"
engine = create_engine(connection_string)
cursor = connection.cursor()

# Юнит 3. Предварительный анализ данных

1. Напишите запрос, который посчитает количество вакансий в нашей базе (вакансии находятся в таблице vacancies).

In [4]:
# текст запроса
query_3_1 = '''
SELECT COUNT(*) AS total_vacancies FROM vacancies;
'''

In [5]:
# результат запроса
df = pd.read_sql_query(query_3_1, engine)
df

   total_vacancies
0            49197

2. Напишите запрос, который посчитает количество работодателей (таблица employers).

In [6]:
# текст запроса
query_employers = '''
SELECT COUNT(*) AS total_employers FROM employers;
'''

In [7]:
# результат запроса
df_employers = pd.read_sql_query(query_employers, engine)
df_employers

   total_employers
0            23501

3. Посчитате с помощью запроса количество регионов (таблица areas).

In [8]:
# текст запроса
query_regions = '''
SELECT COUNT(DISTINCT name) AS total_regions FROM areas;
'''

In [9]:
# результат запроса
df_regions = pd.read_sql_query(query_regions, engine)
df_regions

   total_regions
0           1362

4. Посчитате с помощью запроса количество сфер деятельности в базе (таблица industries).

In [10]:
# текст запроса
query_industries = '''
SELECT COUNT(DISTINCT name) AS total_industries FROM industries;
'''

In [11]:
# результат запроса
df_industries = pd.read_sql_query(query_industries, engine)
df_industries

   total_industries
0               294

***

# выводы по предварительному анализу данных
В среднем каждый работодатель выкладывает по 2 вакансии на HeadHunter. В каждом регионе в срднем по 4 сферы деятельности, что может говорить об узко развитом направлении жизнедеятельности региона.

# Юнит 4. Детальный анализ вакансий

1. Напишите запрос, который позволит узнать, сколько (cnt) вакансий в каждом регионе (area).
Отсортируйте по количеству вакансий в порядке убывания.

In [ ]:
# текст запроса
query_vacancies_region = '''
SELECT a.name AS region_name, COUNT(*) AS cnt
FROM vacancies v
JOIN areas a ON v.area_id = a.id
GROUP BY a.name
ORDER BY cnt DESC;
'''

In [ ]:
# результат запроса
df_vacancies_region = pd.read_sql_query(query_vacancies_region, engine)
df_vacancies_region

         region_name   cnt
0             Москва  5333
1    Санкт-Петербург  2851
2              Минск  2112
3        Новосибирск  2006
4             Алматы  1892
..               ...   ...
764       Тарко-Сале     1
765    Новоаннинский     1
766            Бирск     1
767           Сасово     1
768             Анна     1

[769 rows x 2 columns]

2. Напишите запрос, чтобы определить у какого количества вакансий заполнено хотя бы одно из двух полей с зарплатой.

In [ ]:
# текст запроса
query_salary = '''
SELECT COUNT(*) AS vacancies_with_salary
FROM vacancies
WHERE salary_to IS NOT NULL OR salary_from IS NOT NULL;
'''

In [ ]:
# результат запроса
df_salary = pd.read_sql_query(query_salary, engine)
df_salary

   vacancies_with_salary
0                  24073

3. Найдите средние значения для нижней и верхней границы зарплатной вилки. Округлите значения до целого.

In [ ]:
# текст запроса
query_avg_salary = '''
SELECT 
    ROUND(AVG(salary_from)) AS avg_salary_from,
    ROUND(AVG(salary_to)) AS avg_salary_to
FROM vacancies;
'''

In [ ]:
# результат запроса
df_avg_salary = pd.read_sql_query(query_avg_salary, engine)
df_avg_salary

   avg_salary_from  avg_salary_to
0          71065.0       110537.0

4. Напишите запрос, который выведет количество вакансий для каждого сочетания типа рабочего графика (schedule) и типа трудоустройства (employment), используемого в вакансиях. Результат отсортируйте по убыванию количества.

In [ ]:
# текст запроса
query_schedule_employment = '''
SELECT schedule, employment, COUNT(*) AS cnt
FROM vacancies
GROUP BY schedule, employment
ORDER BY cnt DESC;
'''

In [ ]:
# результат запроса
df_schedule_employment = pd.read_sql_query(query_schedule_employment, engine)
df_schedule_employment

            schedule           employment    cnt
0        Полный день     Полная занятость  35367
1   Удаленная работа     Полная занятость   7802
2      Гибкий график     Полная занятость   1593
3   Удаленная работа  Частичная занятость   1312
4     Сменный график     Полная занятость    940
5        Полный день           Стажировка    569
6     Вахтовый метод     Полная занятость    367
7        Полный день  Частичная занятость    347
8      Гибкий график  Частичная занятость    312
9        Полный день     Проектная работа    141
10  Удаленная работа     Проектная работа    133
11     Гибкий график           Стажировка    116
12    Сменный график  Частичная занятость    101
13  Удаленная работа           Стажировка     64
14     Гибкий график     Проектная работа     18
15    Сменный график           Стажировка     12
16    Вахтовый метод     Проектная работа      2
17    Сменный график     Проектная работа      1

5. Напишите запрос, выводящий значения поля Требуемый опыт работы (experience) в порядке возрастания количества вакансий, в которых указан данный вариант опыта.

In [13]:
# текст запроса
query_experience = '''
SELECT experience, COUNT(*) AS cnt
FROM vacancies
GROUP BY experience
ORDER BY cnt ASC;
'''

In [14]:
# результат запроса
df_experience = pd.read_sql_query(query_experience, engine)
df_experience

           experience    cnt
0         Более 6 лет   1337
1           Нет опыта   7197
2       От 3 до 6 лет  14511
3  От 1 года до 3 лет  26152

***

#выводы по детальному анализу вакансий - В целом преобладают вакансии из Москвы, но, максимальная заработная плата, указанная по регионам 110 тыс.руб, большое количество вакансий требует полный рабочий день без удаленного формата работы с опытом более 6 лет, что может говорить о том, что вакансии из Москвы в большинстве указаны без заработной платы, т.к средняя заработная плата в москве - выше.

# Юнит 5. Анализ работодателей

1. Напишите запрос, который позволит узнать, какие работодатели находятся на первом и пятом месте по количеству вакансий.

In [ ]:
# текст запроса
query_top_employers = '''
WITH ranked_employers AS (
    SELECT
        e.name AS employer_name,
        COUNT(*) AS vacancy_count,
        RANK() OVER (ORDER BY COUNT(*) DESC) AS rank
    FROM vacancies v
    JOIN employers e ON v.employer_id = e.id
    GROUP BY e.name
)
SELECT employer_name, vacancy_count, rank
FROM ranked_employers
WHERE rank IN (1, 5);
'''

In [ ]:
# результат запроса
df_top_employers = pd.read_sql_query(query_top_employers, engine)
df_top_employers

   employer_name  vacancy_count  rank
0         Яндекс           1933     1
1  Газпром нефть            331     5

2. Напишите запрос, который для каждого региона выведет количество работодателей и вакансий в нём.
Среди регионов, в которых нет вакансий, найдите тот, в котором наибольшее количество работодателей.

In [ ]:
# текст запроса
query = '''
SELECT a.name
FROM areas a
LEFT JOIN vacancies v ON v.area_id = a.id
WHERE v.id IS NULL
ORDER BY (
    SELECT COUNT(*) FROM employers e WHERE e.area = a.id
) DESC;
'''

In [ ]:
# результат запроса
df = pd.read_sql_query(query, engine)
df

                                        name
0                                     Россия
1                                  Казахстан
2                         Московская область
3                         Краснодарский край
4                                   Беларусь
..                                       ...
588  Красногвардейское (Ставропольский край)
589                                Львовское
590                            Красноуральск
591                                     Очер
592    Светлогорск (Калининградская область)

[593 rows x 1 columns]

3. Для каждого работодателя посчитайте количество регионов, в которых он публикует свои вакансии. Отсортируйте результат по убыванию количества.

In [ ]:
# текст запроса
query = '''
SELECT 
    e.id,
    e.name,
    COUNT(DISTINCT v.area_id) AS regions_count
FROM 
    employers e
JOIN 
    vacancies v ON v.employer_id = e.id
GROUP BY 
    e.id, e.name
ORDER BY 
    regions_count DESC;
'''

In [ ]:
# результат запроса
df = pd.read_sql_query(query, engine)
df

            id                                    name  regions_count
0         1740                                  Яндекс            181
1         2748                              Ростелеком            152
2      5724811                              Спецремонт            116
3      5130287                  Поляков Денис Иванович             88
4      3682876                               ООО ЕФИН              71
...        ...                                     ...            ...
14901   810278                            НПП Авиатрон              1
14902   810313              Центр дистанционных торгов              1
14903   810551  Городские Телекоммуникационные Системы              1
14904   810688                       Введенский, Отель              1
14905   811902              Группа Компаний Автоимпорт              1

[14906 rows x 3 columns]

4. Напишите запрос для подсчёта количества работодателей, у которых не указана сфера деятельности.

In [ ]:
# текст запроса
query = '''
SELECT COUNT(*) AS employers_without_industry
FROM employers e
LEFT JOIN employers_industries ei ON e.id = ei.employer_id
WHERE ei.industry_id IS NULL;
'''

In [ ]:
# результат запроса
df = pd.read_sql_query(query, engine)
df

   employers_without_industry
0                        8419

5. Напишите запрос, чтобы узнать название компании, находящейся на третьем месте в алфавитном списке (по названию) компаний, у которых указано четыре сферы деятельности.

In [ ]:
# текст запроса
query = '''
WITH employer_industry_counts AS (
    SELECT 
        e.id,
        e.name,
        COUNT(DISTINCT ei.industry_id) AS industry_count
    FROM 
        employers e
    LEFT JOIN 
        employers_industries ei ON e.id = ei.employer_id
    GROUP BY 
        e.id, e.name
)
SELECT name
FROM employer_industry_counts
WHERE industry_count = 4
ORDER BY name
LIMIT 1 OFFSET 2;
'''

In [ ]:
# результат запроса
df = pd.read_sql_query(query, engine)
df

   name
0  2ГИС

6. С помощью запроса выясните, у какого количества работодателей в качестве сферы деятельности указана Разработка программного обеспечения.

In [ ]:
# текст запроса
query = '''
SELECT COUNT(DISTINCT ei.employer_id) AS number_of_employers
FROM employers_industries ei
JOIN industries i ON ei.industry_id = i.id
WHERE i.name = 'Разработка программного обеспечения';
'''

In [ ]:
# результат запроса
df = pd.read_sql_query(query, engine)
df

   number_of_employers
0                 3553

7. Для компании «Яндекс» выведите список регионов-миллионников, в которых представлены вакансии компании, вместе с количеством вакансий в этих регионах. Также добавьте строку Total с общим количеством вакансий компании. Результат отсортируйте по возрастанию количества.

Список городов-милионников надо взять [отсюда](https://ru.wikipedia.org/wiki/%D0%93%D0%BE%D1%80%D0%BE%D0%B4%D0%B0-%D0%BC%D0%B8%D0%BB%D0%BB%D0%B8%D0%BE%D0%BD%D0%B5%D1%80%D1%8B_%D0%A0%D0%BE%D1%81%D1%81%D0%B8%D0%B8). 

Если возникнут трудности с этим задание посмотрите материалы модуля  PYTHON-17. Как получать данные из веб-источников и API.

In [ ]:
# результат запроса

***

#выводы по анализу работодателей - в большинстве вакансии выкладывают Техногиганты, такие как Яндекс, пользуясь спросом в больших количествах регионах

# Юнит 6. Предметный анализ

1. Сколько вакансий имеет отношение к данным?

Считаем, что вакансия имеет отношение к данным, если в её названии содержатся слова 'data' или 'данн'.

*Подсказка: Обратите внимание, что названия вакансий могут быть написаны в любом регистре.*

In [22]:
# текст запроса
engine = create_engine('postgresql://user:password@localhost:5432/dbname')

# Проверьте соединение
with engine.connect() as connection:
    result = connection.execute("SELECT 1")
    print(result.fetchone())
with engine.connect() as connection:
    result = pd.read_sql(query, connection)
    print(result)

OperationalError: (psycopg2.OperationalError) connection to server at "localhost" (::1), port 5432 failed: Connection refused (0x0000274D/10061)
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused (0x0000274D/10061)
	Is the server running on that host and accepting TCP/IP connections?

(Background on this error at: https://sqlalche.me/e/20/e3q8)

In [20]:
# результат запроса
result = pd.read_sql(query, engine)
result

TypeError: sqlalchemy.cyextension.immutabledict.immutabledict is not a sequence

2. Сколько есть подходящих вакансий для начинающего дата-сайентиста? 
Будем считать вакансиями для дата-сайентистов такие, в названии которых есть хотя бы одно из следующих сочетаний:
* 'data scientist'
* 'data science'
* 'исследователь данных'
* 'ML' (здесь не нужно брать вакансии по HTML)
* 'machine learning'
* 'машинн%обучен%'

** В следующих заданиях мы продолжим работать с вакансиями по этому условию.*

Считаем вакансиями для специалистов уровня Junior следующие:
* в названии есть слово 'junior' *или*
* требуемый опыт — Нет опыта *или*
* тип трудоустройства — Стажировка.

In [42]:
cursor = connection.cursor()

query = '''
SELECT COUNT(*) FROM vacancies
WHERE
(
    LOWER(name) LIKE '%data scientist%' OR
    LOWER(name) LIKE '%data science%' OR
    LOWER(name) LIKE '%исследователь данных%' OR
    LOWER(name) LIKE '%machine learning%' OR
    LOWER(name) LIKE '%ml%' OR
    LOWER(name) LIKE '%машинн%обучен%'
)
AND name NOT LIKE '%.html%'
AND (
    LOWER(name) LIKE '%junior%' OR
    experience = 'Нет опыта' OR
    employment = 'Стажировка'
)
AND (key_skills NOT ILIKE '%html%')
'''

In [43]:
# результат запроса
cursor.execute(query)
result = cursor.fetchone()
print(f"Количество подходящих вакансий: {result[0]}")

Количество подходящих вакансий: 49

3. Сколько есть вакансий для DS, в которых в качестве ключевого навыка указан SQL или postgres?

** Критерии для отнесения вакансии к DS указаны в предыдущем задании.*

In [58]:
cursor = connection.cursor()

query = '''
SELECT COUNT(*) FROM vacancies
WHERE
(
    -- Общие критерии для всех вакансий
    (
        LOWER(name) LIKE '%data scientist%' OR
        LOWER(name) LIKE '%data science%' OR
        LOWER(name) LIKE '%исследователь данных%' OR
        LOWER(name) LIKE '%machine learning%' OR
        LOWER(name) LIKE '%ml%' OR
        LOWER(name) LIKE '%машинн%обучен%'
    )
)
AND (
    -- Для ML(машинное обучение) исключаем вакансии по HTML
    NOT (
        LOWER(name) LIKE '%ml%'
        AND name NOT LIKE '%.html%'
    )
)
AND key_skills ILIKE '%python%'
'''

In [59]:
connection.rollback()
cursor.execute(query)
result = cursor.fetchone()
print(f"Количество вакансий с требованиями DS и Python: {result[0]}")

Количество вакансий с требованиями DS и Python: 263

4. Проверьте, насколько популярен Python в требованиях работодателей к DS.Для этого вычислите количество вакансий, в которых в качестве ключевого навыка указан Python.

** Это можно сделать помощью запроса, аналогичного предыдущему.*

In [60]:
# текст запроса
cursor = connection.cursor()

query = '''
SELECT COUNT(*) FROM vacancies
WHERE
(
    -- Общие критерии для всех вакансий
    name LIKE '%data scientist%' OR
    name LIKE '%data science%' OR
    name LIKE '%исследователь данных%' OR
    name LIKE '%machine learning%' OR
    name LIKE '%ML%' OR
    name LIKE '%машинн%обучен%'
)
AND (
    -- Для ML исключаем вакансии по HTML
    NOT (name LIKE '%ML%' AND name NOT LIKE '%.html%')
)
AND key_skills ILIKE '%python%'
'''

In [61]:
# результат запроса
connection.rollback()
cursor.execute(query)
result = cursor.fetchone()
print(f"Количество вакансий с требованиями DS и Python: {result[0]}")

Количество вакансий с требованиями DS и Python: 15

5. Сколько ключевых навыков в среднем указывают в вакансиях для DS?
Ответ округлите до двух знаков после точки-разделителя.

In [64]:
# текст запроса
cursor = connection.cursor()

query = '''
SELECT ROUND(AVG(
    CASE 
        WHEN key_skills IS NULL OR key_skills = '' THEN 0
        ELSE LENGTH(key_skills) - LENGTH(REPLACE(key_skills, ',', '')) + 1
    END
), 2)
FROM vacancies
WHERE
(
    name LIKE '%data scientist%' OR
    name LIKE '%data science%' OR
    name LIKE '%исследователь данных%' OR
    name LIKE '%machine learning%' OR
    name LIKE '%ml%' OR
    name LIKE '%машинн%обучен%'
)
'''

In [65]:
# результат запроса
connection.rollback()
cursor.execute(query)
result = cursor.fetchone()
print(f"Среднее количество ключевых навыков у вакансиях для DS: {result[0]}")

Среднее количество ключевых навыков у вакансиях для DS: 0.82

6. Напишите запрос, позволяющий вычислить, какую зарплату для DS в **среднем** указывают для каждого типа требуемого опыта (уникальное значение из поля *experience*). 

При решении задачи примите во внимание следующее:
1. Рассматриваем только вакансии, у которых заполнено хотя бы одно из двух полей с зарплатой.
2. Если заполнены оба поля с зарплатой, то считаем зарплату по каждой вакансии как сумму двух полей, делённую на 2. Если заполнено только одно из полей, то его и считаем зарплатой по вакансии.
3. Если в расчётах участвует null, в результате он тоже даст null (посмотрите, что возвращает запрос select 1 + null). Чтобы избежать этой ситуацию, мы воспользуемся функцией [coalesce](https://postgrespro.ru/docs/postgresql/9.5/functions-conditional#functions-coalesce-nvl-ifnull), которая заменит null на значение, которое мы передадим. Например, посмотрите, что возвращает запрос `select 1 + coalesce(null, 0)`

Выясните, на какую зарплату в среднем может рассчитывать дата-сайентист с опытом работы от 3 до 6 лет. Результат округлите до целого числа.

In [ ]:
# текст запроса

In [ ]:
# результат запроса

***

In [ ]:
# выводы по предметному анализу

# Общий вывод по проекту

#В среднем каждый работодатель размещает около 2 вакансий на HeadHunter, что говорит о умеренной конкуренции и возможной специализации работодателей. В разрезе регионов наблюдается среднее количество по 4 сферы деятельности, что может свидетельствовать о узконаправленной сфере развития региона и специфике его рынка труда.

Наиболее активно представлены вакансии из Москвы, где также зафиксированы максимальные предложения по заработной плате — до 110 тысяч рублей. При этом большинство требований сосредоточены на полном рабочем дне без возможности работы удаленно и с опытом более 6 лет. Это, вероятно, связано с отсутствием конкретной средней зарплаты по регионам, так как средняя по Москве выше.

Важной особенностью является доминирование крупных технологических компаний, таких как Яндекс, которые активно публикуют свои вакансии, особенно в крупных регионах. Это подтверждает высокий спрос на специалистов от ведущих работодателей в сфере технологий.

Дополнительно, для более глубокого понимания рынка труда можно провести дальнейшие исследования, например, анализ динамики количества вакансий и зарплат со временем, прогнозировать будущие тренды на рынке труда, а также рассматривать возможности расширения выбора вакансий или повышение конкуренции. Такие шаги помогут более точно оценить развитие профессиональной сферы и принять стратегические решения.

Если пожелаете, я могу помочь подготовить конкретные сценарии развития, прогнозы или провести дополнительные исследования на основе имеющихся данных.